### PR TITLE
Prettier integration

### PR DESCRIPTION
**Pull request by moshekatz**
| Q                    | A
| -------------------- | ---
| Bug fix?             | ✔︎/✘
| New feature?         | ✔︎/✘
| Breaking change?     | ✔︎/✘
| Deprecations?        | ✔︎/✘
| Tests added?         | ✔︎/✘
| Documentation added? | ✔︎/✘
| Fixed issues         |

### CODE REVIEW

**Comment by sahariko** [comment]
While I agree that moving the responsibility over code styling to Prettier is the way to go, I would caution against using Prettier as part of ESLint, since its ESLint plugin is notoriously hella slow, even more so in bigger projects.

Consider setting up Prettier independently from ESLint, and running its checks/fixes on their own (maybe as part of the same script for convenience's sake).

**Comment by sashalavron** [comment]
> While I agree that moving the responsibility over code styling to Prettier is the way to go, I would caution against using Prettier as part of ESLint, since its ESLint plugin is notoriously hella slow, even more so in bigger projects.
> 
> Consider setting up Prettier independently from ESLint, and running its checks/fixes on their own (maybe as part of the same script for convenience's sake).

@sahariko this is what we aim to do, it's not a prettier **plugin**, it's a set of _eslint rules_ which basically turns off conflicting formatting rules. the prettier will format & check stuff as _separate layer (independently)_

we had the same topic and we followed the same logic you mentioned 💪 

https://prettier.io/docs/en/integrating-with-linters.html

**Comment by sahariko** [comment]
Awesome, although I think you're missing my point a little bit - what I meant was that running Prettier as part of ESLint's process via a dedicated plugin (which is what this PR does), is significantly slower and memory-intensive than running Prettier's CLI directly.

**Comment by sashalavron** [comment]
> Awesome, although I think you're missing my point a little bit - what I meant was that running Prettier as part of ESLint's process via a dedicated plugin (which is what this PR does), is significantly slower and memory-intensive than running Prettier's CLI directly.

@sahariko yeah I got it completely! and thats one of the reasons we don't use Prettier as part of eslint process. we are on the same page

this pr uses [**eslint-config-prettier**](https://github.com/prettier/eslint-config-prettier) (which basically turns off eslint rules and thats it) and you are referring to the eslint [**plugin**](https://github.com/prettier/eslint-plugin-prettier) prettier, they are 2 different things

**Comment by sahariko** [comment]
Ahhhh gotcha, my bad!

Godspeed 🚀

**Pull request closed without merging**
